export let fakeFood = [
    {
        title: "Healthy Meal Plan",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/sk8cuOLm9KdT4vptADQu_TRXKYVz0A5EvAH1rI6CtHdzQQ5W33L_GYfUCJvsBDshaMFO-juwV-RX16usLcxHTd2n2XemNDHRs36zY7HPEz7obX0AjAzwpk3_rHBO6w324styeqh3sg=w2400",
        price: 23.99,
        category: "lunch",
    },
    {
        title: "Fried Chicken Bento",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/v85Ulb4YLOt6APu_cDIIWF2hMZ77hjxJtpnG_ocXGuEGnfgfIaEZ_c6ZG91BpJy5jJ_Fr3LupF8LFvRj-UYChaYzni3H9Yp00FiinAgTfyEHLFF-tgDuLE_vYjDfTEvzvphSDdCcyw=w2400",
        price: 9.99,
        category: "lunch",
    },
    {
        title: "Tarragon-Rubbed-Salmon",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/0O4LmfNYAkrRqM8dU4ANYhvNQhFEoWN_2872eNDCwCspL4fjRX0l_AdZeb4z3bAJwxyfvyreFkYg2mHcDlm-E6hQEtSmY1UQjo6u9j2v0P6OZ1JsGPBINldlhdY_LhiiU7oZ9IuO0w=w2400",
        price: 6.99,
        category: "lunch",
    },
    {
        title: "Beef Steak",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/Ar1zAHz73Nmj_IsyeEA-ul6oPM5AalhY7YeNF57519Xn-R31nh_yO2nI_jyIRlTJIo7vCVFOa3eR7M-j8c5pITtga9T_DAO_Vcm_Sq22BsVJH7rdlD-XME5gZQ4Fy_9guoomOhRPVw=w2400",
        price: 15.99,
        category: "lunch",
    },
    {
        title: "Honey-Soy-Glazed Salmon With Pepp ",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/5tVceF9bXvCRho78xYLc_3LrJtZ8vPNC_upTpFAL0WBfG4hn4jfCc-n0MdRtoohs9yTfTqf37GTfcC0LcpS573Chq1JLDF8JUcvnYBluf2NLsABfpfFHkeEJ1nKYx8PxX2eNeFNEiA=w2400",
        price: 15.99,
        category: "lunch",
    },
    {
        title: "Indian Lunch",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/uKGhaflDr_xIgtbkmXuc6wKLkHBcp861HLSh4pjoAN2b9WE3-SjXoSSWbBa8cqx_W9bTFzxTDg13qFmAxSPZy_1add8IU6jG7ztomrkT-QIoruzFz13UNVcN2ay_ABc66OQLb8pA2Q=w2400",
        price: 8.99,
        category: "lunch",
    },
    {
        title: "Bagel and Cream Cheese",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/ch-LMMuqTjOcM9ySg_-iTXUlfVGa4NlHrJ_rvyNnEJ2ngpixjKnpxdXsWv8jvkZ718Kbpkn5Ho4zLP3nnl_nes6OOwR72JT9ryoQZ7AA5-M5Vi6zAr7H8P_1gwiNBp09E5Yk3YIdBw=w2400",
        price: 6.99,
        category: "breakfast",
    },
    {
        title: "Breakfast Sandwich",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/QHsgzvVLXm2lheCtXFcYxn4bcwIob4ien3XUEf9m_h5tYiyPpEFjBPQnZIBuC1cC-QMiNMcrsMOdGr5syfE_fgyiZq0zJjOM1vlu8gIUVmEJA8CDs2ndDn95GoxWYSGUczgu_JaZOA=w2400",
        price: 9.99,
        category: "breakfast",
    },
    {
        title: "Eggs Benedict",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/oN0_Ex4wN-_t07J7glRHj9yYkIjtVn7I4qN2RF76xrQV2kx4lrrUlfpDZwvc0JgEVJltlDbnyIIGuUIThNhqSK05ky9Ak0o8tpBouhALQtyUhb6NAP75EtlCZwlL533SICJpgN1S0w=w2400",
        price: 8.99,
        category: "breakfast",
    },
    {
        title: "Toast Croissant Fried Egg ",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/UbpIcbBsQw0KZM3rAZScC_URlFeKhnJkc84k1VFSOG1rP1j087PaevW6d6oWRKseBDSzEweC8Hut1fkTu7gal6MOT7SMmkgWJglBkbJJ7XJ2Lb3xEHvgljrS7tTCs9z5Fi9-oIyDsg=w2400",
        price: 6.99,
        category: "breakfast",
    },
    {
        title: "Baked Chicken",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/Sr0RuoKj6q4L-3ggsr9FgY02H1E6nL_wGr90dIoEB82wZ62THx2jzH1xhj5jOWIsw0b5VUi3aoNNtTDfUylOqBo42qUINik6a5Kubi5aWyEApbJR4RvE7-WZbZ0GR7Qn-XPxKaT6iA=w2400",
        price: 10.99,
        category: "breakfast",
    },
    {
        title: "Full Breakfast Fried Egg Toast Brunch",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/Dx7QataL8nayOKGEw7mZXFCmsulO3wQM9w9uoSBLoBOf3Dg6MMnbVp0Y3xTenmYs5qsvRT3MVf1Sbz88yeLAtmYimnSNmG71t6geltYgJXQYFm4hay___wnkzKnLG9ohordKA1s3RQ=w2400",
        price: 3.99,
        category: "breakfast",
    },
    {
        title: "Salmon With Grapefruit And lenti Salad",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/BnYXl3IiCtJRy7TbLuxL5vzCnQiMkZZX_i1erEXzTwXUFYG45aHaLAAYgFSj0rB6tucw-4Eje8Xq-aBZCNdOvLXOWymDvHs3uDeh9LizxkOfwIv5sytSVEX-TsDzhW0K34sni3ghpg=w2400",
        price: 9.99,
        category: "dinner",
    },
    {
        title: "French fries with cheese",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/uFsSqKdoiK7BAXB8Rv_Qz4SJliw_SvP8o2fDPtCMeP1DWCeM-mvFeTAgdlrRGBHgfT_-zwlWg05fnmk2vU1wkCMufTkwMyo8lmP9NBQGZk5qEBzFTBQ1jxkrWady4ndpZuygbgswgw=w2400",
        price: 8.99,
        category: "dinner",
    },
    {
        title: "Lemony Salmon Piccata",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/2r9CWxkIub8Po4UcokcAQBt1pSzmFgChGYo1lZpMIR-a4Klg5-qSzGDs7bxcwZSjQv0vZ68K5ynjnUweMw94iqg9FmJ3kj-w59BohQ1fxsbKjz2uLiewXogLHZuMJiGHdnUzSZ0ZfQ=w2400",
        price: 10.99,
        category: "dinner",
    },
    {
        title: "Garlic Butter Baked Salmon",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/CpsraaqbIoqB0oBlzRt_CPqhSZsX7abcZFrpVMB7cTsSx-C75Ih8B7W7Fj5yDpuS25if-55zzKs7o2eJH6-_64NvCAX1Zb4Tc1_5escVmY0PS3fd3KyieKcF8twcvh36B2gHCHMpNQ=w2400",
        price: 6.99,
        category: "dinner",
    },
    {
        title: "pork Tenderloin With Quinoa Pilaf",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/tr3TYpaMHvrLt_IUQTTTC--lI5M17obZRWCSLSTOZZWakJuD6TlLE9iQGnjlKVOYqE9qRHRZUyligQt5Bg45kLykl-fveBT31uDsT_HwEXf9oCPbVHF5buwLZxl6fNGu6aqKRdkqig=w2400",
        price: 12.99,
        category: "dinner",
    },
    {
        title: "Baked Chicken",
        description: "How We Dream About Our Future",
        img: "https://lh3.googleusercontent.com/xIKYQ7_hwNXLiAKVKsfPtg-aaNS-vGsDRLwHWfRIOEKFxBH3qStLP_zhChSh-4JJHC9s21qqzRUkZoI38Uz9Xy6MHV5A8sbenH6jyLk9vqc45iRqNSWKPloww9J33mwDQ6B2UTCljg=w2400",
        price: 9.99,
        category: "dinner",
    },

]